planscore/after_upload.py
planscore/tests/test_after_upload.py
planscore/tests/test_upload_fields.py
planscore/upload_fields.py
planscore/website/__init__.py

Also set up CORS configuration on `planscore` bucket in preparation. Part of #13.

Prepared single-plan static page with means to see plan score

---

Makefile
circle.yml
lambda.py
planscore/after_upload.py
planscore/districts.py
planscore/tests/test_after_upload.py
planscore/tests/test_districts.py

To support larger states like North Carolina, we’ll need to run processes longer than the AWS 5 minute limit. A new `PlanScore-RunDistricts` function will process each district in parallel, and will be invoked as an event to run in the background. Currently, this new function no-ops into the logs but it can be observed. Part of #21.

Dark-launch new PlanScore-RunDistricts function

---

Makefile
circle.yml
planscore/districts.py
planscore/score.py
planscore/tests/test_districts.py
planscore/tests/test_score.py

Leaving adequate time (15sec) for follow-up invocation, and scrunching event data down with ASCII-encoded gzip compression. Now we’re recursing. Part of #21.

Fixed some problems in self-invoking Lambda function

---

planscore/districts.py
planscore/tests/test_districts.py

Use tile geometry intersections and LRU cache to reduce overall amount of work done in `planscore.districts`. Add a bunch of tests for various spatial relationships between districts, tiles, and precincts.

Speed up district processing

---

Makefile
data/sample-NC-1-992/index.json
debug-site.py
planscore/website/static/plan.js
planscore/website/templates/plan.html
tests.js

Adds a `plan.description` property expected to contain HTML, and shows it on Plan pages if it exists along with last-modified dates.

Add space for plan descriptions

---

Makefile
deploy.py
lambda.py
planscore/after_upload.py
planscore/callback.py
planscore/tests/test_after_upload.py
planscore/tests/test_callback.py
planscore/website/__init__.py
setup-localstack.py

Insert a new step immediately before AfterUpload extracts data, so that a plan uploader does not experience a lengthy delay before being redirected to a score page.

Split AfterUpload step

---

README.md

This adds to the installation instructions, documentation for Ubuntu 16 and 17.
Ubuntu 16's repositories include GDAL 1.x while 2.x requires the Unstable PPA. Alternately, mention is made of installing from source and then using -I and -L flags much as described under OSX.
Ubuntu 17 comes with GDAL 2.x and simple `apt-get` instructions are provided.

install doc, added Ubuntu 16+17

---

data/sample-NC-simulations/index.json
planscore/score.py
planscore/tests/test_score.py
planscore/website/static/plan.js
tests.js

Display the right numbers generated by simulation process. Ignore the confidence intervals for now, but use their presence to determine what to show.

Handle output from many EG simulations

---

deploy.py
planscore/after_upload.py
planscore/data.py
planscore/districts.py
planscore/tests/test_after_upload.py
planscore/tests/test_districts.py

We were seeing some AWS Lambda `RequestEntityTooLargeException` errors with complex or detailed plans. This PR modifies the event structure to include an S3 key in place of a geometry WKT literal.

Pass district geometries via S3

---

circle.yml

Ask Circle to push to S3. For now I’ve created a bucket visible here: http://planscore.org-static-site.s3-website-us-east-1.amazonaws.com/
- For later, update our Cloudfront distribution to merge this bucket and the one controlled by the master branch.
- This change may also make Github pages redundant, so consider renaming this branch from `gh-pages` to `static-site`.

Added deployment to AWS S3

---

planscore/score.py
planscore/tests/test_score.py

Calculate EG at 1-point vote swing intervals from -5 to +5, output everything in the result summary dict with standard deviations for multiple-simulation models:
"summary": {
"Efficiency Gap": 0.0820,
"Efficiency Gap SD": 0.044,
"Efficiency Gap +1 Dem": 0.0620,
"Efficiency Gap +1 Rep": 0.1020,
"Efficiency Gap +2 Dem": 0.0420,
"Efficiency Gap +2 Rep": 0.1220,
"Efficiency Gap +3 Dem": 0.022,
"Efficiency Gap +3 Rep": 0.1420,
"Efficiency Gap +4 Dem": 0.002004,
"Efficiency Gap +4 Rep": 0.1620,
"Efficiency Gap +5 Dem": -0.01799,
"Efficiency Gap +5 Rep": 0.1820,
"Efficiency Gap +1 Dem SD": 0.044,
"Efficiency Gap +1 Rep SD": 0.04401,
"Efficiency Gap +2 Dem SD": 0.0440,
"Efficiency Gap +2 Rep SD": 0.044,
"Efficiency Gap +3 Dem SD": 0.04401,
"Efficiency Gap +3 Rep SD": 0.04401,
"Efficiency Gap +4 …

Added sensitivity testing data to summary

---

planscore/after_upload.py
planscore/compactness/__init__.py
planscore/compactness/smallestenclosingcircle.py
planscore/districts.py
planscore/score.py
planscore/tests/data/uploads/sample-plan/districts/0.json
planscore/tests/data/uploads/sample-plan/districts/1.json
planscore/tests/test_after_upload.py
planscore/tests/test_compactness.py
planscore/tests/test_districts.py
planscore/tests/test_score.py
planscore/tests/test_smallestenclosingcircle.py
setup.py

Using definitions from https://github.com/cicero-data/compactness-stats/wiki and @nayuki’s implementation of smallest bounding circle. Scores appear under `compactness` in index JSON.

Add Reock and Polsby-Popper compactness scores

---

planscore/score.py
planscore/tests/test_score.py

MMD is another useful partisan symmetry metric. It doesn’t seem to have the same sensitivity to vote swings so just include a single value.

Add Mean/Median calculation to output

---

planscore/after_upload.py
planscore/districts.py
planscore/tests/test_districts.py
planscore/tests/test_upload_fields.py
planscore/upload_fields.py

`private` was too restrictive when used between accounts.

Replaced ACL=private with ACL=bucket-owner-full-control

---

README.md
deploy.py
lambda.py
planscore/constants.py
planscore/districts.py
planscore/empty_queue.py
planscore/tests/test_districts.py
planscore/tests/test_util.py
planscore/util.py
setup-localstack.py
setup.py

Log units of work for individual tiles so this can be measured and optimized. Introduces new dependency on Amazon SQS, with required `SQS_QUEUEURL` environment variable for existing `PlanScore-RunDistrict` and new `PlanScore-EmptyQueue` Lambda functions.

Add logging for tile timing

---

index.js6

Merging into the State Senate support in PR #227 a new workaround for a few data-poor years on the front page. As described in #228, selecting State Senate when 2004 or 2014 would be the new "snap-to" year, will be rewritten as 2002 and 2012 where we have more data to display.

#228 front page fudgeYearIfNoData mod re State Senate 2004/2014

---

deploy.py
planscore/tests/test_upload_fields.py
planscore/upload_fields.py
planscore/website/templates/upload.html

Introduce key & secret for an IAM user that can only perform S3 uploads. Routes around the problem of expiring IAM roles when used in S3 pre-signed POSTs.

Presign uploads with IAM upload-only user

---

index.js6

This PR would bring in the behavior described in #238   On the front page, clicking a state would proceed directly to the given state+bound+year and there would be no popup.
Per #238 this intentionally leaves the current-behavior programming in place, until we decide which behavior is preferred.

Issue 238 front page: click state = go to state

---

planscore/after_upload.py
planscore/callback.py
planscore/data.py
planscore/observe.py
planscore/score.py
planscore/tests/test_after_upload.py
planscore/tests/test_callback.py
planscore/tests/test_data.py
planscore/tests/test_observe.py
planscore/tests/test_score.py

Parallelize on hundreds of tiles instead of dozens of districts. Keep the old way around just in case, for now.

Use new, faster tile-based scoring method instead of districts

---

planscore/prepare_state.py
planscore/tests/test_prepare_state.py

Stop building at one zoom level, and create an adaptive model for new tile-based process.

Build multizoom tiles in prepare-state

---

north_carolina/index.js6
north_carolina/index.src.html

This very hacky approach introduces a North Carolina table that’s only shown when NC + U.S. House are selected.

Added NC-only table with 2016/18 U.S. House details

---

data/sample-NC5.1/index.json
planscore/website/static/plan.js
tests.js

Currently, there is no user-accessible way to add these descriptions.

Added plan.what_score_description_text() for user-supplied descriptions

---

README.md
deploy.py
planscore/constants.py
planscore/tests/test_util.py
planscore/tests/test_website.py
planscore/util.py
planscore/website/__init__.py
setup-localstack.py

New versions of [localstack](https://github.com/localstack/localstack) include an implementation of API Gateway so stop using a Flask proxy implementation. Add method and integration updates to deployment script, and get slightly smarter about localstack URLs.

Upgrade localstack

---

index.src.html

Callout states suddenly missing due to a recent change in HighMaps. 
A one-line change to pin to 8.0.4 fixes the issue in local testing, but we need a refresher on how the CI setup works -- I got a failing build notification from circleCI on this branch, and my assumption is that if we merged into `static-site` we would see the same issue, though not sure.
Here's the error:

Pin HighMaps.js version

---

planscore/matrix.py
planscore/tests/test_matrix.py
planscore/tests/test_score.py

Uploaded plans may include blank districts, such as the all-water fake districts included with U.S. Census shapefiles.

Handle scoring of districts with no votes

---

.circleci/config.yml
Makefile

Werkzeug update introduced Python 3.7+ `dataclasses` dependency, so switch to older Python during build step maintain compatibility with Python 3.6 runtime.
Also introduces `cf-canary` deployment to prevent broken production deployments.

Downgrade build Python to fix Circle deploy

---

planscore/website/static/plan.js
planscore/website/templates/plan.html

Stylistic change that's subjective.  Right-aligning these cells makes it easier IMO to compare single-digit to multi-digit numbers. The heading cells match alignment of the rows.
Before (top) / After (bottom)

right-align numeric table cells

---

planscore/website/static/plan.js
planscore/website/templates/plan.html

Really felt like there needed to be a better way to correlate the table rows with the map above. (and vice versa)
I went with styling that felt decent to me (mimic table row hover and strengthen the stroke-width), but I'm totally open to trying other ideas out.
GIF demo:

add hover interaction between map and table rows

---

planscore/website/static/plan.css
planscore/website/static/plan.js
planscore/website/templates/plan.html

fixes #361 
I also chose to set a height on the table, allowing you to browse the full table while the map remains on screen. 
I dropped bootstrap's table-responsive as it conflicts (and also has other opinions on text-wrapping).
After interacting with the page/table/map a bit I'm pretty pleased with the feel. Open to suggestions/tweaks of course.

adopt responsive table styling, courtesy of the jehl-table

---

planscore/website/__init__.py
planscore/website/templates/plan.html

Current loading waterfall:
The network request for the geometry data only starts once the plan json is done (red annotation). The pink annotation shows the 300ms-ish of opportunity.
If we start a preload for the geometry at the same time as we start the plan json, we save some time.

perf: preload the geometry

---

planscore/website/static/upload.js
planscore/website/templates/upload.html

(followup to #376)
from https://github.com/PlanScore/PlanScore/issues/365#issuecomment-873624408
> After merging #376 I occasionally see the error message “Didn't connect to PlanScore API server.” I think this might be confusing for a user though I like the one-button improvement we’ve got now. How can we accommodate a slow server response so a user gets a more helpful message?
As I mentioned, this issue is due to a race of the /upload GET against the file selection.
In this PR, I add an extra 7 seconds of grace time after file-selection before the user sees an error.
impl-wise: there were a few ways to do this, but switching the XHR to fetch had a few benefits:
* in my local dev the /upload endpoint was 404ing, but oddly that didn't even hit the `request.onerror` callback. (tbh, i forget …

add extra grace time on upload form interaction

---

planscore/observe.py
planscore/tests/test_observe.py
planscore/website/templates/plan.html

Followup to #375: index JSON was getting stuck in cache when pre-fetched despite presence of cache-control directives. Remove it for now, maybe revisit in #378?

Do not pre-fetch index JSON

---

data/sample-NC2019/index-preread-start.json
planscore/preread.py
planscore/website/static/annotate-new.js
planscore/website/templates/annotate.html

the page just polls for updates now. no more asking the user to refresh. (ref #365) 
I went for something pretty lo-fi. If the 'message' from the backend is the same, I just append some ellipsis. 
Especially since the text is center-aligned, it's fairly visible.
I'm happy to upgrade this to something more obvious if you want, but it seemed like a nice, minimal start. ;)

annotate: add polling

---

planscore/website/static/plan.js

These are the only uses of 'wasted' I spot.  Matches the replacement done in https://github.com/PlanScore/FrontPage/commit/261234d90d84c460cc44c674a024c9867ae710ff

rename wasted to inefficient

---

planscore/observe.py
planscore/tests/test_observe.py
planscore/website/static/plan.js

Saw an input file with an empty district. Although scores might be weird, these should still complete and correctly report zero population and vote counts.

Fix hang when an empty district is provided

---

planscore/website/static/plan.js
planscore/website/templates/plan.html
tests.js

- Used description for H1 insted of redundant plan type text, so that library curator can determine display name
- Implemented state name and house name in header, based on prior `get_plan_type_text()` function
- Moved resources inside top-level section so they don't appear on load failure
- Added website base prefix to resource link icons

Tweaked plan summary and resource link display

---

cdk-scoring/cdk-scoring.py
planscore/api_upload.py

`GET /upload/interactive` is now the unauthorized endpoint, and `GET /upload` is no longer implemented. Followup to #408.

Hide /upload behind API token 

---

cdk-scoring/cdk-scoring.py
lambda.py
planscore/postread_callback.py
planscore/postread_intermediate.py
planscore/tests/test_postread_callback.py

It wasn't enough to extend the timeout for PostreadCallback, needed to make the whole slow part async in PostreadIntermediate.

Eliminate multistep timeouts

---

planscore/website/templates/plan.html

@migurski noticed a missing icon on plan pages, was missing the `/images/` path.

Fix missing icon on plan pages

---

planscore/data.py
planscore/website/static/plan.js
planscore/website/templates/plan.html

Uses no curves for FTVA races, like this US House plan example:

Expose FTVA races at bottom of score pages

---

planscore/website/static/plan.js

AZ has five currently-valid FTVA races.

Slice FTVA races to no more than four to accommodate Arizona

---

planscore/observe.py
planscore/postread_intermediate.py

Immediately fail when either API upload or ObserveTiles catches an exception.

Improved error handling

---

planscore/website/static/annotate-new.js
planscore/website/static/plan.js

Response to migration guide: https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/
Wait for https://github.com/PlanScore/FrontPage/pull/102

Update label map tiles from Stamen to Stadia

---

planscore/data.py
planscore/postread_callback.py
planscore/tests/test_data.py
planscore/tests/test_postread_callback.py

These tokens were being omitted from the logs, bring them back.
Also, track execution IDs to make it easier to connect tokens to API access methods via logs.

Add missing auth token to multistep API requests
