PlanScore/PlanScore

Makefile, circle.yml, upload.html
Added an upload form at `upload.html` that pushes to S3, and created primitive deployment process. Closes #3.
=> Added S3 upload form

.gitignore, Makefile, circle.yml, planscore/after_upload.py, planscore/tests/test_after_upload.py, planscore/tests/test_upload_fields.py, planscore/tests/test_util.py, planscore/upload_fields.py, planscore/util.py
Currently, just verify that some number of bytes was privately uploaded in a new function. Part of #6.
=> Respond to uploaded plans

planscore/after_upload.py, planscore/prepare_state.py, planscore/tests/test_after_upload.py, planscore/tests/test_prepare_state.py, setup.py
Added format and uploader for storage of precinct data in gzipped GeoJSON tiles, and started poking at it in uploads. Part of #6.
=> Added storage format for precinct data

planscore/after_upload.py, planscore/score.py, planscore/tests/test_after_upload.py, planscore/tests/test_website.py, planscore/website/__init__.py, planscore/website/static/plan.js, planscore/website/templates/plan.html
Created tabular plan view with current fields. Part of #13.
=> Stubbed out simple plan page

planscore/score.py, planscore/tests/test_score.py, planscore/website/static/plan.js, planscore/website/templates/plan.html
=> Added efficiency gap display output

planscore/after_upload.py, planscore/data.py, planscore/tests/test_after_upload.py, planscore/tests/test_data.py
=> Added geometry GeoJSON file for visual map preview

planscore/after_upload.py, planscore/tests/test_after_upload.py, planscore/tests/test_website.py, planscore/website/__init__.py, planscore/website/static/plan.js, planscore/website/templates/plan.html
=> Added visible map to plan page

planscore/after_upload.py, planscore/data.py, planscore/districts.py, planscore/tests/test_after_upload.py, planscore/tests/test_data.py, planscore/tests/test_districts.py
Data needs to go someplace beyond the logs. Part of #21.
=> Started writing district state to S3 as part of PlanScore-RunDistricts

circle.yml, planscore/after_upload.py, planscore/districts.py, planscore/score.py, planscore/tests/test_after_upload.py
=> Removed old plan scoring logic and cleaned up one NC bug

circle.yml, planscore/after_upload.py, planscore/districts.py, planscore/prepare_state.py, planscore/score.py, planscore/tests/test_after_upload.py, planscore/tests/test_score.py, planscore/website/static/plan.js, planscore/website/templates/plan.html, setup.py
=> Introduced display for real-life races on plan pages

Makefile, deploy.py, setup-localstack.py
Remove chatter from Makefile and use the same publishing code for local and live Lambdas.
=> Added deploy.py script for local and production Lambda

CONTRIBUTING.md
=> Updated performance goals

planscore/website/__init__.py, planscore/website/static/plan.js
Better check for Node.JS / Common.JS module.exports in `planscore/website/plan.js` to prevent browsers from complaining
Added S3 region to `planscore/website/__init__.py`'s `get_localstack_lambda()` for local dev
=> Website bug fixes

planscore/after_upload.py, planscore/districts.py, planscore/tests/test_after_upload.py, planscore/tests/test_districts.py
Added exception where a Partial gets a geometry instance instead of an S3 key.
=> Corrected geometry key/WKT representation ambiguity

planscore/data.py, planscore/score.py, planscore/tests/test_data.py, planscore/tests/test_score.py
Useful for copying to spreadsheets when debugging models.
=> Add plaintext output to final score

planscore/after_upload.py, planscore/constants.py, planscore/tests/test_after_upload.py
Stubbed in some expected paths for Wisconsin once we have all three houses modeled.
=> Added state house seat counts to guess correct models

planscore/score.py, planscore/tests/test_score.py
Calculate Gelman & King Partisan Bias, but don’t measure sensitivity.
=> Add Partisan Bias calculation

circle.yml, planscore/website/static/plan.js, planscore/website/templates/patternlibrary.html, planscore/website/templates/plan.html
Adds pattern library JS with new plan histogram feature. Currently functional only for US House plans.
=> Add plan histogram

planscore/website/__init__.py, planscore/website/templates/efficiencygap.html, planscore/website/templates/friends-resources.html, planscore/website/templates/historical-data.html, planscore/website/templates/meanmedian.html, planscore/website/templates/partisanbias.html
Adds pages for each metric and historical data, all currently living in `static-site` branch.
=> Add content pages

planscore/website/static/plan.js, planscore/website/templates/plan.html
Added error, fixed links, added "Predicted" qualifier for vote counts.
=> Update plan page text

data/sample-NC5.1/index.json, planscore/after_upload.py, planscore/constants.py, planscore/data.py, planscore/tests/test_after_upload.py, planscore/tests/test_data.py, planscore/tests/test_districts.py, planscore/website/static/plan.js, tests.js
Adds `data.Model` class and changes how model paths are stored and passed.
=> Show score model info on plan page

planscore/website/static/plan.js, planscore/website/templates/plan.html, tests.js
Also hiding compactness score columns for now.
=> Adjusted plan pages to show Mean-Median Difference

planscore/website/static/plan.js, tests.js
Show percentages for CVAP, ACS 5-year, and D/R predicted votes.
=> Display upload percentages on score page

planscore/website/templates/about.html
Duplicate word ("the" on line 14)
=> Update text in about.html

_common/styles/general.scss, index.scss
Fixes from @tsinn for text underlines and vertical margin around tab blocks
=> Static site tsinn updates

htmlpartials/footer.js
=> stack contact info on phones

planscore/after_upload.py, planscore/constants.py, planscore/tests/test_after_upload.py
Preparing to run many more tiles in parallel with a threaded `fan_out_tile_lambdas()`.
=> Thread tile lambdas

planscore/constants.py, planscore/data.py, planscore/observe.py, planscore/tests/test_data.py, planscore/tests/test_observe.py, planscore/tiles.py
Use the expected delay until first complete tile to do geometric scores.
=> Add compactness measures to PlanScore-ObserveTiles

planscore/after_upload.py, planscore/data.py, planscore/districts.py, planscore/score.py, planscore/tests/test_after_upload.py, planscore/tests/test_districts.py, planscore/tests/test_score.py
=> Stop running states by district

.circleci/config.yml, tests.js
Also added Node tests to standard testing run so they aren’t skipped again.
=> Fixed node test

deploy.py, lambda.py, planscore/constants.py, planscore/preread.py, planscore/preread_followup.py, planscore/tests/test_preread.py, planscore/tests/test_preread_followup.py, planscore/tests/test_upload_fields_new.py, planscore/upload_fields_new.py, planscore/website/__init__.py, planscore/website/static/annotate-new.js, planscore/website/templates/annotate-new.html, planscore/website/templates/upload-new.html
Added new upload path with non-functional incumbency feature.
=> Add district incumbencies on dark path

planscore/matrix.py, planscore/score.py, planscore/tests/test_matrix.py, planscore/tests/test_score.py
Corrected remaining division-by-zero problems found in Michigan sample data.
=> Update handling of empty districts

planscore/score.py, planscore/tests/test_score.py
Just in upload summary for now.
=> Added fraction of positive results of all three scores

data/sample-NC-festblocks/index.json, planscore/website/static/plan.js
Only for newer scores with “Positives” in summary dict.
=> Replaced score error display with positives on score page

planscore/matrix.py, planscore/score.py, planscore/tests/test_matrix.py, planscore/tests/test_score.py, setup.py
Useful for checking matrix internals when debugging scoring and stats.
=> Add matrix debug script

planscore/matrix.py, planscore/tests/test_matrix.py
Change EG calculation to match Eric’s no-turnout evaluation runs.
=> Averaged turnout across all plan districts

planscore/matrix.py, planscore/tests/test_matrix.py
=> Reinstated turnout across all plan districts

deploy.py, planscore/data.py, planscore/tests/test_data.py
Useful for model matrix debugging
=> Add commit SHA to data.Upload

planscore/website/templates/plan.html
=> fix grammar typo: let => lets. fixes #230

.circleci/config.yml, planscore/website/static/plan.js, tests.js
Expecting the small refactor to has_incumbency to fix the current test failure. Update: yay they do.
Also I removed the custom NODE_PATH thing by just using relative paths in the require() calls. that's more idiomatic anyhow.
=> extract plan_has_incumbency method, fix broken test

.circleci/config.yml, cdk-content/cdk-content.py
A new `.gz` file was causing problems. Fix the bug and improve error output so future ones can be found.
=> Fixed deploy

.circleci/config.yml, .gitignore, Makefile, lambda.py, planscore/update_metrics.py, setup.py
Read from Athena scoring logs, write to Google Sheets.
=> Add write to GDocs metrics dashboard

planscore/website/static/plan.js, tests.js
fixes #370. ref #368 
It's a bit overengineered, but it does the trick across the multitude of field names. 🤷
=> shorten table heading titles

planscore/website/static/plan.css, planscore/website/static/plan.js, planscore/website/templates/annotate.html, planscore/website/templates/plan.html, tests.js
fixes #366 
Here's how it looks w/ dev styles:
and with current styles:
=> adjust plan headings for readability

planscore/website/static/upload.js, planscore/website/templates/upload.html
in this PR are the bullet points of "upload page" from #365 
<details><summary>screenshots:</summary>
current page: https://planscore.org/upload.html
</details>
=> upload page upgrades: layout & button interaction

cdk-deploy.sh, planscore/api_upload.py, planscore/authorizer.py, planscore/data.py, planscore/tests/test_data.py, planscore/update_metrics.py
These will be useful to later see how many maps are being uploaded via DRA, etc.
=> Log auth tokens for later

planscore/score.py, planscore/tests/test_score.py
Bug reported for NE congressional delegation with all-R winners.
=> Repair declination for one-party states

cdk-scoring/cdk-scoring.py
Might affect https://github.com/PlanScore/PlanScore/issues/391
=> Added cache and CORS policies to S3 and Cloudfront

cdk-content/cdk-content.py, data/sample-FL-declination/index.json, planscore/website/__init__.py, planscore/website/static/plan.js, planscore/website/templates/patternlibrary.html, planscore/website/templates/plan.html, tests.js
Release this after https://github.com/PlanScore/FrontPage/pull/19 is merged
=> Show declination scores on plan pages

planscore/website/static/plan.js, tests.js
Adjust strong vs. lean colors to reflect flippiness
=> Add flip likelihood for district display

cdk-scoring/cdk-scoring.py, planscore/constants.py
Keeping the previous `/upload` resource available for this PR
=> Added /upload/interactive API resource

planscore/website/static/plan.js, planscore/website/templates/plan.html
=> Support plan metadata

planscore/website/static/plan.js, tests.js
=> Add vote share next to seat share

planscore/data.py, planscore/website/static/plan.js
=> Add Virginia 2020 data, update ME and ND data

planscore/data.py
=> Update PA data

planscore/data.py
=> Update Florida with backfilled VEST data

planscore/data.py, planscore/website/static/annotate-new.js, planscore/website/templates/annotate.html
=> Move prediction method choice above the fold

planscore/data.py
=> Update MS data to VEST

planscore/tests/test_util.py, planscore/util.py
Identify `POLYGON Z` geoms as polygonal
=> Handle 2.5D geometries

cdk-scoring/cdk-scoring.py
Follow-up to https://github.com/PlanScore/PlanScore/pull/484
=> Null out production domains

cdk-scoring/cdk-scoring.py
=> Re-add production domains in reverse

.circleci/config.yml, cdk-content/cdk-content.py, cdk-scoring/cdk-scoring.py, planscore/website/templates/patternlibrary.html, tests.js
Synched with https://github.com/PlanScore/FrontPage/pull/100
=> Clean up domain swap and CLC/PlanScore content

planscore/data.py, planscore/website/static/annotate-new.js
Corrected the `is_public` index.
=> Fix model version link from VersionParameters tuple

planscore/data.py
Coordinate with https://github.com/PlanScore/National-Input-Data/pull/26
=> Add GA 2024 pvote

planscore/data.py
Coordinate with https://github.com/PlanScore/National-Input-Data/pull/27
=> Added MD 2024 pvote

planscore/data.py
Coordinate with https://github.com/PlanScore/National-Input-Data/pull/28
=> Add RDH 2024 pvote 

planscore/data.py
Coordinate with https://github.com/PlanScore/National-Input-Data/pull/30
=> Add NYT state 2024 pvote

planscore/data.py
Merge after https://github.com/PlanScore/National-Input-Data/pull/34
=> Add AR, CT, KS, and RI 2024 pvote

planscore/data.py
Wait for https://github.com/PlanScore/National-Input-Data/pull/35
=> Add Florida 2024 pvote
